[package]
name = "frontend"
version = "0.0.0"
edition = "2021"

#[dev-dependencies]
#console_error_panic_hook = { workspace = true }

[dependencies]
web-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-cli = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
gloo = { workspace = true }
reqwasm = { workspace = true }

invidious = { workspace = true }
rustytube-error = { workspace = true }
config = { workspace = true }

num-format = { workspace = true }

console_error_panic_hook = { workspace = true }
stylist = { workspace = true }

[dependencies.leptos]
workspace = true
features = ["csr", "nightly"]

[dependencies.leptos_router]
workspace = true
features = ["csr", "nightly"]
