[package]
name = "frontend"
version = "0.0.0"
edition = "2021"

[dependencies]

web-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-cli = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
gloo = { workspace = true }

invidious = { workspace = true }
rustytube_error = { workspace = true }
config = { workspace = true }

[dependencies.leptos]
workspace = true
features = ["csr", "nightly"]
