[workspace]
members = ["src-tauri", "frontend", "shared/*"]

[workspace.package]
version = "0.1.0"
authors = ["Stephen Power"]
description = "A cross-platform Youtube frontend built with Tauri, Yew. Designed with Tailwind."
license = "GPL"
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"

[workspace.dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-cli = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen-test = "0.3.37"
js-sys = "0.3.64"
reqwasm = "0.5.0"
ron = "0.8.0"
csv = "1.2.2"
humantime = "2.1.0"
chrono = "0.4.26"
toml = "0.7.6"
num-format = "0.4.4"
console_error_panic_hook = "0.1.7"

[workspace.dependencies.tauri]
version = "1.4.1"
features = []

[workspace.dependencies.leptos]
version = "0.4.6"
features = ["csr", "nightly"]

[workspace.dependencies.serde]
version = "1.0.183"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.105"

[workspace.dependencies.web-sys]
version = "0.3.64"
features=[
    "DataTransfer", "Element", "Navigator", "HtmlAnchorElement",
    "HtmlButtonElement", "HtmlDialogElement", "Navigator", "Clipboard",
    "HtmlDivElement", "HtmlDocument", "HtmlInputElement", "HtmlLabelElement",
    "HtmlTextAreaElement", "HtmlParagraphElement", "HtmlVideoElement", "Event", "EventTarget",
    "MouseEvent", "InputEvent", "KeyEvent", "KeyboardEvent", "KeyboardEventInit",
    "TouchEvent", "TouchList", "Touch", "DomTokenList", "Performance", "Window",
    "MediaSource"
]

[workspace.dependencies.gloo]
version = "0.9.0"
features = ["file", "futures"]

[workspace.dependencies.tauri-sys]
git = "https://github.com/opensourcecheemsburgers/tauri-sys"

[workspace.dependencies.invidious]
path = "shared/invidious"

[workspace.dependencies.figment]
version = "0.10.10"
features = ["toml"]

[workspace.dependencies.rustytube_error]
path = "shared/error"

[workspace.dependencies.utils]
path = "shared/utils"

[workspace.dependencies.config]
path = "shared/config"